apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-sample # Deploymentの名前
  labels:
    app: go-sample # Deploymentのタグ
spec:
# 生成される2つのpodに設定
  replicas: 2
  selector:
    matchLabels:
      app: go-sample # DeploymentによりこのPodが生成されたとの目印
  template:
    metadata:
      labels:
        app: go-sample # Podテンプレート内のコンテナと一致させること
    spec:
      containers:
        - name: go-sample # Podテンプレート内のコンテナの名前
          image: go-sample-image  # ローカルで作成したDockerイメージを使用
          imagePullPolicy: IfNotPresent # ローカルのイメージを使用するため、imagePullPolicyをIfNotPresentに設定
          ports:
            - containerPort: 8080 # コンテナのポートは8080






